packages/gke/README.md
packages/gke/__tests__/class.ts
packages/gke/__tests__/validate.ts
packages/gke/crd/backendconfigs.yaml
packages/gke/package.json
packages/gke/tsconfig.json

Add BackendConfig CRD for GKE Ingress

feat: Add gke package

---

packages/crd-generate/src/generate.ts
packages/sealed-secrets/README.md
packages/sealed-secrets/__tests__/class.ts
packages/sealed-secrets/__tests__/validate.ts
packages/sealed-secrets/crd/sealed-secrets.yaml
packages/sealed-secrets/package-lock.json
packages/sealed-secrets/package.json
packages/sealed-secrets/tsconfig.json

Add [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets)

feat(sealed-secrets): add sealed-secrets model

---

packages/base/src/__tests__/model.ts
packages/base/src/model.ts

fix(base): Move apiVersion and kind to the front

---

packages/crd-generate/src/generate.ts

Closes #21
---
[#hacktoberfest](https://hacktoberfest.digitalocean.com/). Can this Pull Request be labeled "hacktoberfest-accepted"?

feat(crd-generate): allow apiextensions.k8s.io/v1 api version too

---

packages/prometheus-operator/README.md
packages/prometheus-operator/__tests__/class.ts
packages/prometheus-operator/__tests__/validate.ts
packages/prometheus-operator/package-lock.json
packages/prometheus-operator/package.json
packages/prometheus-operator/tsconfig.json

Add support for [Prometheus operator](https://github.com/prometheus-operator/prometheus-operator/) models

feat: add prometheus-operator models

---

packages/base/src/__tests__/model.ts
packages/base/src/index.ts
packages/base/src/model.ts
packages/crd-generate/src/generate.ts
packages/openapi-generate/src/generators/definition.ts

fix(base): Fix key order in YAML

---

packages/export-map/src/generate.ts

- Only generate paths for `/index` exports.
- Add `./*` as fallback export.

refactor(export-map): Generate directory entries only

---

package-lock.json
packages/crd-generate/src/generators/definition.ts
packages/generate/package-lock.json
packages/generate/package.json
packages/generate/src/interface.ts
packages/generate/src/schema.ts
packages/generate/src/types.ts
packages/kubernetes-models/__tests__/validate.ts
packages/openapi-generate/src/generators/schema.ts

feat(generate): Allow null in JSON schema

---

packages/validate/src/__tests__/ajv.ts
packages/validate/src/ajv.ts

https://github.com/ajv-validator/ajv-formats/pull/31

fix(validate): Fix byte format validator

---

.changeset/young-moons-listen.md
README.md
packages/cilium/README.md
packages/cilium/__tests__/class.ts
packages/cilium/__tests__/validate.ts
packages/cilium/package.json
packages/cilium/tsconfig.json
pnpm-lock.yaml

feat(cilium): Add package

---

.changeset/tender-colts-judge.md
third-party/argo-cd/__tests__/class.ts
third-party/argo-cd/package.json

fix(argo-cd): Fix missing `ApplicationSet` CRD

---

.changeset/green-kids-cover.md
README.md
pnpm-lock.yaml
third-party/shipwright/README.md
third-party/shipwright/__tests__/class.ts
third-party/shipwright/package.json
third-party/shipwright/tsconfig.json

Hi @tommy351, I really appreciate your work here.👍
This PR adds CRD-generated models for [Shipwright](https://shipwright.io/). See the committed README.md and CHANGELOG.md. Shipwright is a framework for building container images.
~~I would be happy if you could release this version as 0.9.0. After that, I would create updates for 0.10.0 and 0.11.0.~~
~~Also if the changes between these versions are super small and add only additional fields, I would like to go with a 0.9 release first because I know that this version is still used in many environments.~~
~~Let me know if this is fine for you.~~
edit: It uses the latest Shipwright 0.11.0 CRDs now. See my comment below.

feat: Add new Shipwright models

---

.changeset/warm-files-vanish.md
third-party/argo-cd/package.json

feat(argo-cd): Update CRD version to v2.8.4

---

.changeset/funny-seas-enjoy.md
pnpm-lock.yaml
third-party/nats/README.md
third-party/nats/__tests__/class.ts
third-party/nats/package.json
third-party/nats/tsconfig.json

Introduce NACK CRDs.
https://github.com/nats-io/nack

feat(third-party/nats): introduce

---

.changeset/fruity-jobs-sit.md
README.md
pnpm-lock.yaml
third-party/kyverno/README.md
third-party/kyverno/__tests__/class.ts
third-party/kyverno/package.json
third-party/kyverno/tsconfig.json

The PR is for introducing the Kyverno related CRDs.
https://kyverno.io/

feat: introduce the  Kyverno models

---

CONTRIBUTING.md
README.md

- chore(CONTRIBUTEING): adjust the new crd command
- chore(README): adjust the formatting issue

chore: adjust the README and CONTRIBUTEING documents

---

.changeset/four-cats-hang.md
README.md
pnpm-lock.yaml
third-party/spicedb/README.md
third-party/spicedb/__tests__/class.ts
third-party/spicedb/package.json
third-party/spicedb/tsconfig.json

- feat(third-party): introduce spicedb
- test(third-party): add spicedb related
- chore: add the README for spiceDB

feat: introduce the spiceDB models

---

.changeset/wet-cups-tie.md
README.md
pnpm-lock.yaml
third-party/hierarchical-namespaces/__tests__/class.ts
third-party/hierarchical-namespaces/package.json
third-party/hierarchical-namespaces/tsconfig.json

The PR is for introducing the Hierarchical Namespaces CRDs.
https://github.com/kubernetes-sigs/hierarchical-namespaces/tree/v1.1/api/v1alpha2

feat(third-party/hierarchical-namespaces): Introduce package

---

.changeset/fluffy-taxis-greet.md
pnpm-lock.yaml
third-party/karpenter/__tests__/class.ts
third-party/karpenter/package.json
third-party/karpenter/tsconfig.json

https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.35.4/pkg/apis/crds/karpenter.sh_nodepools.yaml
https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.35.4/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.35.4/pkg/apis/crds/karpenter.sh_nodeclaims.yaml

feat(third-party/karpenter): Introduce package

---

.changeset/swift-cars-check.md
core/validate/package.json
core/validate/src/runtime/re2.ts
pnpm-lock.yaml
third-party/postgres-operator/__tests__/validate.ts
utils/generate/package.json
utils/generate/src/pattern.ts
utils/generate/src/schema.ts

feat(generate): Use re2 for RegExp unsupported by JS

---

.changeset/purple-tigers-tease.md
.eslintrc
first-party/apimachinery/package.json
first-party/apimachinery/scripts/generate.ts
pnpm-lock.yaml
utils/crd-generate/package.json
utils/crd-generate/src/generate.ts
utils/crd-generate/src/generators/alias.ts
utils/generate/package.json
utils/generate/src/interface.ts
utils/generate/src/schema.ts
utils/openapi-generate/package.json
utils/openapi-generate/src/context.ts
utils/openapi-generate/src/generate.ts
utils/openapi-generate/src/generators/definition.ts

refactor: Replace lodash with es-toolkit
